language: php

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files

php:
  - 7.3
  - 7.4
  - 8.0

env:
  - LARAVEL_VERSION=7.x-dev TESTBENCH=5.x-dev
  - LARAVEL_VERSION=8.x-dev TESTBENCH=6.x-dev

jobs:
  exclude:
    - php: 7.2
      env: LARAVEL_VERSION=8.x-dev TESTBENCH=6.x-dev

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - phpenv config-rm xdebug.ini
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update --prefer-dist
  - composer require "orchestra/testbench:${TESTBENCH}" --no-update --prefer-dist

install: travis_retry composer install --no-interaction --prefer-dist

before_script: phpenv config-add ~/xdebug.ini

script: vendor/bin/phpunit

notifications:
  email: false
